engines:
  eslint:
    enabled: true

ratings:
  paths:
  - "**.js"

exclude_paths:
- "gulpfile.babel.js"
- "index.js"
- ".tasks/*.js"
- "scripts/**"
- "LICENSE"
- "**.json"
- "**.ts"
- "**.md"
- "**.yml"
- "*.sln*"
